Implement prebuild job for Docker image workflow
Added prebuild job to check for DockerHub credentials.

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,8 +1,6 @@
 name: Docker
 
 on:
-  schedule:
-    - cron: '31 22 * * 0'
   push:
     branches: [main, dev]
     # Publish semver tags as releases.
@@ -12,8 +10,18 @@ on:
   workflow_dispatch:
 
 jobs:
+  prebuild:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Should build?
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "The DOCKERHUB_USERNAME secret is missing."
+            exit 1
+          fi
 
   build:
+    needs: [prebuild]
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -39,6 +47,13 @@ jobs:
           echo "platforms=${{ matrix.dockerfile == 'multiarch' && 'linux/amd64,linux/arm64,linux/arm/v7' || 'linux/amd64' }}" >> $GITHUB_OUTPUT
           echo "arch=${{ matrix.dockerfile == 'multiarch' && 'amd64,aarch64,armhf' || 'amd64' }}" >> $GITHUB_OUTPUT
 
+      - name: Login to DockerHub
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
       - name: Log into registry ghcr.io
         if: github.event_name != 'pull_request'
         uses: docker/login-action@v3
@@ -63,6 +78,7 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: |
+            ${{ secrets.DOCKERHUB_USERNAME }}/wyze-bridge
             ghcr.io/${{ github.repository }}
           flavor: |
             latest=auto
